services:
  - type: web
    name: tt-fop-parser
    runtime: python
    plan: free
    rootDir: parser-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
